openapi: 3.0.3
info:
  title: Webhooks for My Monorepo
  version: 0.1.0

paths:
  /webhooks/health:
    post:
      summary: Receive health status notifications
      description: |
        This describes the webhook request that **our system** will send to **your** endpoint
        when health status changes (or для періодичного ping'у).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../components/schemas/Health.yaml'
      responses:
        '200':
          description: Successfully processed
        '204':
          description: Successfully processed (no content)
