name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What exactly is not working?
      placeholder: Briefly describe the problem
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: 1. ... 2. ...
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: false
