openapi: 3.0.3
info:
  title: HCC Services Platform Public API
  version: 0.1.0
servers:
  - url: https://api.example.com

paths:
  /health:
    $ref: './paths/health.yaml'

components:
  schemas:
    Error:
      $ref: '../components/schemas/Error.yaml'
    Health:
      $ref: '../components/schemas/Health.yaml'
